vault:
  global:
    enabled: true
  
  server:
    enabled: true
    ui:
      enabled: true
    service:
      type: ClusterIP
    dataStorage:
      enabled: true
      size: 1Gi
      storageClass: local-path
    ha:
      enabled: false
      
    # Configure startup probe instead of readiness/liveness
    # This gives Vault time to start up without failing health checks
    startupProbe:
      enabled: true
      failureThreshold: 12
      initialDelaySeconds: 10
      periodSeconds: 10
    
    # Disable readiness/liveness probes since we're using startup probe
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false

  injector:
    enabled: true

  csi:
    enabled: true