global:
  enabled: true

server:
  enabled: true
  ui:
    enabled: true
  service:
    type: ClusterIP
  dataStorage:
    enabled: true
    storageClass: standard
  ha:
    enabled: false
injector:
  enabled: true
csi:
  enabled: true
tls:
  enabled: false