service:
  type: ClusterIP
ingressRoute:
  dashboard:
    enabled: false
ports:
  web:
    port: 80
    expose: true
    exposedPort: 80
  websecure:
    port: 443
    expose: true
    exposedPort: 443
    tls:
      enabled: true
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    ingressEndpoint:
      publishedService: true
      pathOverride: "traefik/traefik"