apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: development

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: ict

commonAnnotations:
  argocd-image-updater.argoproj.io/image-list: ict=ghcr.io/indy-center/controller-tools
  argocd-image-updater.argoproj.io/ict.pull-secret: pullsecret:argocd/ghcr-secret
  argocd-image-updater.argoproj.io/ict.update-strategy: latest 