apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  dnsNames:
    - argocd.chasingthe.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 