apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.3/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.2/manifests/install.yaml
  - ingress-route.yaml
  - certificate.yaml

patches:
  - path: cmd-params-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
  - path: cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: registries-conf-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-image-updater-config
  - path: image-updater-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-image-updater-config