apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.3/manifests/install.yaml
  - ingress-route.yaml

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm