apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-db
  namespace: production
spec:
  instances: 1
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      version: "16.1"
  
  # Resource management
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  # Configure storage
  storage:
    size: 1Gi
    storageClass: local-path

  # Bootstrap configuration
  bootstrap:
    initdb:
      database: whoami
      owner: whoami_user
      secret:
        name: test-db-app