minio:
  mode: standalone
  persistence:
    size: 10Gi
    storageClass: local-path
  
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 200m

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    path: /
    hosts:
      - minio.chasingthe.cloud
    tls:
      - secretName: minio-tls
        hosts:
          - minio.chasingthe.cloud

  consoleIngress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    path: /
    hosts:
      - minio.chasingthe.cloud
    tls:
      - secretName: minio-console-tls
        hosts:
          - minio.chasingthe.cloud