apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ict-db
  namespace: production
spec:
  instances: 1
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  storage:
    size: 1Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: ict

  backup:
    barmanObjectStore:
      destinationPath: "file:///backup"
      endpointURL: ""
      serverName: ict-db
      wal:
        compression: gzip
        maxParallel: 1
    retentionPolicy: "7d"

  # Add volume for backups
  volumes:
    - name: backup-volume
      persistentVolumeClaim:
        claimName: ict-db-backup
  volumeMounts:
    - name: backup-volume
      mountPath: "/backup" 