infisical-standalone:
  enabled: true
  name: infisical
  autoDatabaseSchemaMigration: true
  
  replicaCount: 1
  
  image:
    repository: infisical/infisical
    tag: "v0.46.2-postgres"
    pullPolicy: IfNotPresent

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    path: /api/status/health

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    path: /api/status/health

  ingress:
    enabled: false

  nginx:
    enabled: false

  controller:
    enabled: false

  postgresql:
    enabled: true
    auth:
      username: infisical
      database: infisical

  redis:
    enabled: true
    architecture: standalone 