apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Project for user applications
  sourceRepos:
    - https://github.com/cr0wst/chasingthecloud.git
  destinations:
    - namespace: development
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: cert-manager.io
      kind: Certificate
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*' 
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/cr0wst/chasingthecloud.git
      revision: HEAD
      directories:
      - path: apps/*/overlays/development
      files:
      - path: "apps/*/overlays/development/app-config.yaml"
  template:
    metadata:
      name: '{{ index (splitList "/" .path.path) 1 }}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{ with index .files.path 0 }}{{ with .contents | fromYaml }}{{ with .annotations }}{{ get . "argocd-image-updater.argoproj.io/image-list" }}{{ end }}{{ end }}{{ end }}'
        argocd-image-updater.argoproj.io/ict.pull-secret: '{{ with index .files.path 0 }}{{ with .contents | fromYaml }}{{ with .annotations }}{{ get . "argocd-image-updater.argoproj.io/ict.pull-secret" }}{{ end }}{{ end }}{{ end }}'
        argocd-image-updater.argoproj.io/ict.update-strategy: '{{ with index .files.path 0 }}{{ with .contents | fromYaml }}{{ with .annotations }}{{ get . "argocd-image-updater.argoproj.io/ict.update-strategy" }}{{ end }}{{ end }}{{ end }}'
        argocd-image-updater.argoproj.io/write-back-method: '{{ with index .files.path 0 }}{{ with .contents | fromYaml }}{{ with .annotations }}{{ get . "argocd-image-updater.argoproj.io/write-back-method" }}{{ end }}{{ end }}{{ end }}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/cr0wst/chasingthecloud.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: development
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true