apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Project for user applications
  sourceRepos:
    - https://github.com/cr0wst/chasingthecloud.git
  destinations:
    - namespace: development
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: cert-manager.io
      kind: Certificate
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*' 
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/cr0wst/chasingthecloud.git
      revision: HEAD
      files:
      - path: "apps/*/overlays/development/app-config.yaml"
  template:
    metadata:
      name: '{{ base (dir .path) }}'
      annotations: '{{ (fromYaml .contents).annotations }}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/cr0wst/chasingthecloud.git
        targetRevision: HEAD
        path: '{{ dir .path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: development
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{ (fromYaml .contents).annotations."argocd-image-updater.argoproj.io/image-list" }}'
        argocd-image-updater.argoproj.io/ict.pull-secret: '{{ (fromYaml .contents).annotations."argocd-image-updater.argoproj.io/ict.pull-secret" }}'
        argocd-image-updater.argoproj.io/ict.update-strategy: '{{ (fromYaml .contents).annotations."argocd-image-updater.argoproj.io/ict.update-strategy" }}'
        argocd-image-updater.argoproj.io/write-back-method: '{{ (fromYaml .contents).annotations."argocd-image-updater.argoproj.io/write-back-method" }}'