apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ict-db
  namespace: production
spec:
  instances: 1
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "64MB"
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  
  storage:
    size: 1Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: ict 