name: Deploy Infrastructure
on:
  push:
    branches:
      - main
jobs:
  deploy-traefik:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: "Docker Stack Deploy: Traefik"
        uses: cssnr/stack-deploy-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          ssh_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          file: "infrastructure/traefik-stack.yaml"
          name: "traefik"
  deploy-swarmpit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: "Docker Stack Deploy: Swarmpit"
        uses: cssnr/stack-deploy-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          ssh_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          file: "infrastructure/swarmpit-stack.yaml"
          name: "swarmpit"
